### ISSUE TITLE
testBuilderDeltaUsingRelaxedRuleBug343256 fails randomly

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.resources#19] opened 2022-03-29 15:56 UTC
See 
- https://download.eclipse.org/eclipse/downloads/drops4/I20220327-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html
- https://ci.eclipse.org/platform/job/eclipse.platform.resources/job/PR-15/2/testReport/junit/org.eclipse.core.tests.internal.builders/AllTests/testBuilderDeltaUsingRelaxedRuleBug343256/

I can see it locally failing every ~10 time.

```
  org.eclipse.core.tests.internal.builders.RelaxedSchedRuleBuilderTest 
| testBuilderDeltaUsingRelaxedRuleBug343256 | Failure | 

Error observed: junit.framework.AssertionFailedError: 1.2. expected:<1> but was:<0>junit.framework.AssertionFailedError: Error observed: junit.framework.AssertionFailedError: 1.2. expected:<1> but was:<0>
at org.eclipse.core.tests.harness.CoreTest.fail(CoreTest.java:74)
at o rg.eclipse.core.tests.internal.builders.RelaxedSchedRuleBuilderTest.testBuilderDeltaUsingRelaxedRuleBug343256(RelaxedSchedRuleBuilderTest.java:341)
```

Output from Jenkins:
```
!ENTRY org.eclipse.core.tests.resources 1 0 2022-03-29 12:44:47.936
!MESSAGE [testBuilderDeltaUsingRelaxedRuleBug343256] setUp

!ENTRY org.eclipse.core.tests.resources 4 0 2022-03-29 12:44:48.951
!MESSAGE [testBuilderDeltaUsingRelaxedRuleBug343256] Some job is still running or waiting to run: 'Building'/org.eclipse.core.internal.events.AutoBuildJob, 'IProject.build()'/org.eclipse.core.tests.internal.builders.RelaxedSchedRuleBuilderTest$7

!ENTRY org.eclipse.core.resources 4 2 2022-03-29 12:44:49.057
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
junit.framework.AssertionFailedError: 1.2. expected:<1> but was:<0>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:377)
	at org.eclipse.core.tests.internal.builders.RelaxedSchedRuleBuilderTest$6.build(RelaxedSchedRuleBuilderTest.java:293)
	at org.eclipse.core.tests.internal.builders.TestBuilder.build(TestBuilder.java:116)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:988)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:253)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:310)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:399)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:402)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:513)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:461)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:543)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:517)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:413)
	at org.eclipse.core.tests.internal.builders.RelaxedSchedRuleBuilderTest$7.run(RelaxedSchedRuleBuilderTest.java:306)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.jobs 4 2 2022-03-29 12:44:49.059
!MESSAGE An internal error occurred during: "IProject.build()".
!STACK 0
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.fail(Assert.java:64)
	at junit.framework.TestCase.fail(TestCase.java:230)
	at org.eclipse.core.tests.internal.builders.RelaxedSchedRuleBuilderTest$7.run(RelaxedSchedRuleBuilderTest.java:315)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.tests.resources 1 0 2022-03-29 12:44:50.106
!MESSAGE [testBuilderDeltaUsingRelaxedRuleBug343256] tearDown
```

**Comment by iloveeclipse** [comment] 2022-04-19 08:20
Still happened:
https://download.eclipse.org/eclipse/downloads/drops4/I20220418-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html
```
Caused by: junit.framework.AssertionFailedError: 1.2:
/testBuildDeltaUsingRelaxedRuleBug343256[~]: {} expected:<1> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.core.tests.internal.builders.RelaxedSchedRuleBuilderTest$6.build(RelaxedSchedRuleBuilderTest.java:300)
at org.eclipse.core.tests.internal.builders.TestBuilder.build(TestBuilder.java:116)
at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1024)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:311)
at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:400)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:514)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:462)
at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:544)
at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:521)
at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:417)
at org.eclipse.core.tests.internal.builders.RelaxedSchedRuleBuilderTest$7.run(RelaxedSchedRuleBuilderTest.java:314)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by jukzi** [comment] 2022-04-25 12:52
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220421-1910/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-win32-java11_win32.win32.x86_64_11.html

**Comment by jukzi** [comment] 2022-04-25 12:53
also 
https://download.eclipse.org/eclipse/downloads/drops4/I20220424-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-win32-java11_win32.win32.x86_64_11.html

**Comment by jukzi** [comment] 2022-04-25 12:53
this fails frequently :(

**Comment by jukzi** [comment] 2022-04-29 07:42
failed again randomly - but i think it's only a unrelated NPE in FreezeMonitor:
https://download.eclipse.org/eclipse/downloads/drops4/I20220428-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html

```
java.lang.AssertionError: Test logged exception
at org.eclipse.core.tests.resources.ResourceTest.lambda$8(ResourceTest.java:1022)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.eclipse.core.tests.resources.ResourceTest.assertNoErrorsLogged(ResourceTest.java:1020)
at org.eclipse.core.tests.internal.builders.RelaxedSchedRuleBuilderTest.testBuilderDeltaUsingRelaxedRuleBug343256(RelaxedSchedRuleBuilderTest.java:356)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
at org.eclipse.test.EclipseTestRunner.runTests(EclipseTestRunner.java:226)
at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:202)
at org.eclipse.test.CoreTestApplication.runTests(CoreTestApplication.java:52)
at org.eclipse.test.CoreTestApplication.run(CoreTestApplication.java:35)
at org.eclipse.test.CoreTestApplication.start(CoreTestApplication.java:43)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
at org.eclipse.core.launcher.Main.main(Main.java:44)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.management.ThreadInfo.getThreadName()" because "threadInfo" is null
at org.eclipse.core.tests.resources.FreezeMonitor$1.run(FreezeMonitor.java:51)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by mickaelistria** [comment] 2022-05-02 12:07
@iloveeclipse do you remember this test was failing so frequently a few months ago, or whether it does seem like a regression somewhere?

**Comment by iloveeclipse** [comment] 2022-05-02 14:46
As far as I can remember, that is related to recent changes for default encoding support, starting with commit 532fc55835c8c161a751c2c9ff63a5cc82dd79ce . There we have added a project validation job, and I believe the scheduling of that job or related code might have introduce this test instability.

**Comment by mickaelistria** [comment] 2022-05-03 08:35
@iloveeclipse OK. What should we do then? Just tweaking the tests to ignore the particular error?

**Comment by iloveeclipse** [comment] 2022-05-03 08:39
Ideally we should understand why it fails & fix.

**Comment by mickaelistria** [comment] 2022-05-03 08:50
I think it's supposed to be fixed with https://github.com/eclipse-platform/eclipse.platform.resources/commit/32eae0b8061fc73865220dcbc94434873d7c7de3 now. Should we close now and reopen if needed?

**Comment by iloveeclipse** [comment] 2022-05-03 09:00
If it is fixed now, sure. I assumed that it is still not fixed.

**Comment by mickaelistria** [comment] 2022-05-03 09:05
> If it is fixed now, sure

No failure since https://github.com/eclipse-platform/eclipse.platform.resources/commit/32eae0b8061fc73865220dcbc94434873d7c7de3 was merged.

**Closed by mickaelistria** 2022-05-03 09:05 UTC
