### ISSUE TITLE
random failing org.eclipse.core.tests.resources.IProjectTest.testProjectDeletionOpenDefaultOutOfSync

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.resources#117] opened 2022-05-07 05:31 UTC
https://download.eclipse.org/eclipse/downloads/drops4/I20220506-0640/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
junit.framework.AssertionFailedError: 6.2
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.TestCase.fail(TestCase.java:223)
at org.eclipse.core.tests.resources.IProjectTest.testProjectDeletionOpenDefaultOutOfSync(IProjectTest.java:2127)
```

**Comment by akurtakov** [comment] 2022-06-08 10:43
Duplicate of #151

**Closed by akurtakov** 2022-06-08 10:43 UTC
